---
name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-11

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install asdf plugin tester
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: xterrafile version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
